/* eslint-disable prettier/prettier */
import { PrismaClient } from '@prisma/client';

const countries = [
  { code: 'AF', name: 'Afghanistan', emoji: '🇦🇫' },
  { code: 'AX', name: '\u00c5land Islands', emoji: '🇦🇽' },
  { code: 'AL', name: 'Albania', emoji: '🇦🇱' },
  { code: 'DZ', name: 'Algeria', emoji: '🇩🇿' },
  { code: 'AS', name: 'American Samoa', emoji: '🇦🇸' },
  { code: 'AD', name: 'Andorra', emoji: '🇦🇩' },
  { code: 'AO', name: 'Angola', emoji: '🇦🇴' },
  { code: 'AI', name: 'Anguilla', emoji: '🇦🇮' },
  { code: 'AQ', name: 'Antarctica', emoji: '🇦🇶' },
  { code: 'AG', name: 'Antigua and Barbuda', emoji: '🇦🇬' },
  { code: 'AR', name: 'Argentina', emoji: '🇦🇷' },
  { code: 'AM', name: 'Armenia', emoji: '🇦🇲' },
  { code: 'AW', name: 'Aruba', emoji: '🇦🇼' },
  { code: 'AU', name: 'Australia', emoji: '🇦🇺' },
  { code: 'AT', name: 'Austria', emoji: '🇦🇹' },
  { code: 'AZ', name: 'Azerbaijan', emoji: '🇦🇿' },
  { code: 'BS', name: 'Bahamas', emoji: '🇧🇸' },
  { code: 'BH', name: 'Bahrain', emoji: '🇧🇭' },
  { code: 'BD', name: 'Bangladesh', emoji: '🇧🇩' },
  { code: 'BB', name: 'Barbados', emoji: '🇧🇧' },
  { code: 'BY', name: 'Belarus', emoji: '🇧🇾' },
  { code: 'BE', name: 'Belgium', emoji: '🇧🇪' },
  { code: 'BZ', name: 'Belize', emoji: '🇧🇿' },
  { code: 'BJ', name: 'Benin', emoji: '🇧🇯' },
  { code: 'BM', name: 'Bermuda', emoji: '🇧🇲' },
  { code: 'BT', name: 'Bhutan', emoji: '🇧🇹' },
  { code: 'BO', name: 'Bolivia', emoji: '🇧🇴' },
  { code: 'BQ', name: 'Bonaire', emoji: '🇧🇶' },
  { code: 'BA', name: 'Bosnia and Herzegovina', emoji: '🇧🇦' },
  { code: 'BW', name: 'Botswana', emoji: '🇧🇼' },
  { code: 'BV', name: 'Bouvet Island', emoji: '🇧🇻' },
  { code: 'BR', name: 'Brazil', emoji: '🇧🇷' },
  { code: 'IO', name: 'British Indian Ocean Territory', emoji: '🇮🇴' },
  { code: 'BN', name: 'Brunei Darussalam', emoji: '🇧🇳' },
  { code: 'BG', name: 'Bulgaria', emoji: '🇧🇬' },
  { code: 'BF', name: 'Burkina Faso', emoji: '🇧🇫' },
  { code: 'BI', name: 'Burundi', emoji: '🇧🇮' },
  { code: 'KH', name: 'Cambodia', emoji: '🇰🇭' },
  { code: 'CM', name: 'Cameroon', emoji: '🇨🇲' },
  { code: 'CA', name: 'Canada', emoji: '🇨🇦' },
  { code: 'CV', name: 'Cape Verde', emoji: '🇨🇻' },
  { code: 'KY', name: 'Cayman Islands', emoji: '🇰🇾' },
  { code: 'CF', name: 'Central African Republic', emoji: '🇨🇫' },
  { code: 'TD', name: 'Chad', emoji: '🇹🇩' },
  { code: 'CL', name: 'Chile', emoji: '🇨🇱' },
  { code: 'CN', name: 'China', emoji: '🇨🇳' },
  { code: 'CX', name: 'Christmas Island', emoji: '🇨🇽' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', emoji: '🇨🇨' },
  { code: 'CO', name: 'Colombia', emoji: '🇨🇴' },
  { code: 'KM', name: 'Comoros', emoji: '🇰🇲' },
  { code: 'CG', name: 'Congo', emoji: '🇨🇬' },
  { code: 'CD', name: 'Democratic Republic of the Congo', emoji: '🇨🇩' },
  { code: 'CK', name: 'Cook Islands', emoji: '🇨🇰' },
  { code: 'CR', name: 'Costa Rica', emoji: '🇨🇷' },
  { code: 'CI', name: 'Croatia', emoji: '🇨🇮' },
  { code: 'HR', name: 'Cuba', emoji: '🇭🇷' },
  { code: 'CU', name: 'Cura\u00e7ao', emoji: '🇨🇺' },
  { code: 'CW', name: 'Cyprus', emoji: '🇨🇼' },
  { code: 'CY', name: 'Czech Republic', emoji: '🇨🇾' },
  { code: 'CZ', name: 'Denmark', emoji: '🇨🇿' },
  { code: 'DK', name: 'Djibouti', emoji: '🇩🇰' },
  { code: 'DJ', name: 'Dominica', emoji: '🇩🇯' },
  { code: 'DM', name: 'Dominican Republic', emoji: '🇩🇲' },
  { code: 'DO', name: 'Ecuador', emoji: '🇩🇴' },
  { code: 'EC', name: 'Egypt', emoji: '🇪🇨' },
  { code: 'EG', name: 'El Salvador', emoji: '🇪🇬' },
  { code: 'SV', name: 'Equatorial Guinea', emoji: '🇸🇻' },
  { code: 'GQ', name: 'Eritrea', emoji: '🇬🇶' },
  { code: 'ER', name: 'Estonia', emoji: '🇪🇷' },
  { code: 'EE', name: 'Ethiopia', emoji: '🇪🇪' },
  { code: 'ET', name: 'Falkland Islands (Malvinas)', emoji: '🇪🇹' },
  { code: 'FK', name: 'Faroe Islands', emoji: '🇫🇰' },
  { code: 'FO', name: 'Fiji', emoji: '🇫🇴' },
  { code: 'FJ', name: 'Finland', emoji: '🇫🇯' },
  { code: 'FI', name: 'France', emoji: '🇫🇮' },
  { code: 'FR', name: 'French Guiana', emoji: '🇫🇷' },
  { code: 'GF', name: 'French Polynesia', emoji: '🇬🇫' },
  { code: 'PF', name: 'French Southern Territories', emoji: '🇵🇫' },
  { code: 'TF', name: 'Gabon', emoji: '🇹🇫' },
  { code: 'GA', name: 'Gambia', emoji: '🇬🇦' },
  { code: 'GM', name: 'Georgia', emoji: '🇬🇲' },
  { code: 'GE', name: 'Germany', emoji: '🇬🇪' },
  { code: 'DE', name: 'Ghana', emoji: '🇩🇪' },
  { code: 'GH', name: 'Gibraltar', emoji: '🇬🇭' },
  { code: 'GI', name: 'Greece', emoji: '🇬🇮' },
  { code: 'GR', name: 'Greenland', emoji: '🇬🇷' },
  { code: 'GL', name: 'Grenada', emoji: '🇬🇱' },
  { code: 'GD', name: 'Guadeloupe', emoji: '🇬🇩' },
  { code: 'GP', name: 'Guam', emoji: '🇬🇵' },
  { code: 'GU', name: 'Guatemala', emoji: '🇬🇺' },
  { code: 'GT', name: 'Guernsey', emoji: '🇬🇹' },
  { code: 'GG', name: 'Guinea', emoji: '🇬🇬' },
  { code: 'GN', name: 'Guinea-Bissau', emoji: '🇬🇳' },
  { code: 'GW', name: 'Guyana', emoji: '🇬🇼' },
  { code: 'GY', name: 'Haiti', emoji: '🇬🇾' },
  { code: 'HT', name: 'Heard Island and McDonald Islands', emoji: '🇭🇹' },
  { code: 'HM', name: 'Holy See (Vatican City State)', emoji: '🇭🇲' },
  { code: 'VA', name: 'Honduras', emoji: '🇻🇦' },
  { code: 'HN', name: 'Hong Kong', emoji: '🇭🇳' },
  { code: 'HK', name: 'Hungary', emoji: '🇭🇰' },
  { code: 'HU', name: 'Iceland', emoji: '🇭🇺' },
  { code: 'IS', name: 'India', emoji: '🇮🇸' },
  { code: 'IN', name: 'Indonesia', emoji: '🇮🇳' },
  { code: 'ID', name: 'Iran', emoji: '🇮🇩' },
  { code: 'IR', name: 'Iraq', emoji: '🇮🇷' },
  { code: 'IQ', name: 'Ireland', emoji: '🇮🇶' },
  { code: 'IE', name: 'Isle of Man', emoji: '🇮🇪' },
  { code: 'IM', name: 'Israel', emoji: '🇮🇲' },
  { code: 'IL', name: 'Italy', emoji: '🇮🇱' },
  { code: 'IT', name: 'Jamaica', emoji: '🇮🇹' },
  { code: 'JM', name: 'Japan', emoji: '🇯🇲' },
  { code: 'JP', name: 'Jersey', emoji: '🇯🇵' },
  { code: 'JE', name: 'Jordan', emoji: '🇯🇪' },
  { code: 'JO', name: 'Kazakhstan', emoji: '🇯🇴' },
  { code: 'KZ', name: 'Kenya', emoji: '🇰🇿' },
  { code: 'KE', name: 'Kiribati', emoji: '🇰🇪' },
  { code: 'KI', name: 'Korea', emoji: '🇰🇮' },
  { code: 'KP', name: 'Kuwait', emoji: '🇰🇵' },
  { code: 'KR', name: 'Kyrgyzstan', emoji: '🇰🇷' },
  { code: 'KW', name: 'Latvia', emoji: '🇰🇼' },
  { code: 'KG', name: 'Lebanon', emoji: '🇰🇬' },
  { code: 'LA', name: 'Lesotho', emoji: '🇱🇦' },
  { code: 'LV', name: 'Liberia', emoji: '🇱🇻' },
  { code: 'LB', name: 'Libya', emoji: '🇱🇧' },
  { code: 'LS', name: 'Liechtenstein', emoji: '🇱🇸' },
  { code: 'LR', name: 'Lithuania', emoji: '🇱🇷' },
  { code: 'LY', name: 'Luxembourg', emoji: '🇱🇾' },
  { code: 'LI', name: 'Macao', emoji: '🇱🇮' },
  { code: 'LT', name: 'Macedonia', emoji: '🇱🇹' },
  { code: 'LU', name: 'Madagascar', emoji: '🇱🇺' },
  { code: 'MO', name: 'Malawi', emoji: '🇲🇴' },
  { code: 'MK', name: 'Malaysia', emoji: '🇲🇰' },
  { code: 'MG', name: 'Maldives', emoji: '🇲🇬' },
  { code: 'MW', name: 'Mali', emoji: '🇲🇼' },
  { code: 'MY', name: 'Malta', emoji: '🇲🇾' },
  { code: 'MV', name: 'Marshall Islands', emoji: '🇲🇻' },
  { code: 'ML', name: 'Martinique', emoji: '🇲🇱' },
  { code: 'MT', name: 'Mauritania', emoji: '🇲🇹' },
  { code: 'MH', name: 'Mauritius', emoji: '🇲🇭' },
  { code: 'MQ', name: 'Mayotte', emoji: '🇲🇶' },
  { code: 'MR', name: 'Mexico', emoji: '🇲🇷' },
  { code: 'MU', name: 'Micronesia', emoji: '🇲🇺' },
  { code: 'YT', name: 'Moldova', emoji: '🇾🇹' },
  { code: 'MX', name: 'Monaco', emoji: '🇲🇽' },
  { code: 'FM', name: 'Mongolia', emoji: '🇫🇲' },
  { code: 'MD', name: 'Montenegro', emoji: '🇲🇩' },
  { code: 'MC', name: 'Montserrat', emoji: '🇲🇨' },
  { code: 'MN', name: 'Morocco', emoji: '🇲🇳' },
  { code: 'ME', name: 'Mozambique', emoji: '🇲🇪' },
  { code: 'MS', name: 'Myanmar', emoji: '🇲🇸' },
  { code: 'MA', name: 'Namibia', emoji: '🇲🇦' },
  { code: 'MZ', name: 'Nauru', emoji: '🇲🇿' },
  { code: 'MM', name: 'Nepal', emoji: '🇲🇲' },
  { code: 'NA', name: 'Netherlands', emoji: '🇳🇦' },
  { code: 'NR', name: 'New Caledonia', emoji: '🇳🇷' },
  { code: 'NP', name: 'New Zealand', emoji: '🇳🇵' },
  { code: 'NL', name: 'Nicaragua', emoji: '🇳🇱' },
  { code: 'NC', name: 'Niger', emoji: '🇳🇨' },
  { code: 'NZ', name: 'Nigeria', emoji: '🇳🇿' },
  { code: 'NI', name: 'Niue', emoji: '🇳🇮' },
  { code: 'NE', name: 'Norfolk Island', emoji: '🇳🇪' },
  { code: 'NG', name: 'Northern Mariana Islands', emoji: '🇳🇬' },
  { code: 'NU', name: 'Norway', emoji: '🇳🇺' },
  { code: 'NF', name: 'Oman', emoji: '🇳🇫' },
  { code: 'MP', name: 'Pakistan', emoji: '🇲🇵' },
  { code: 'NO', name: 'Palau', emoji: '🇳🇴' },
  { code: 'OM', name: 'Palestine', emoji: '🇴🇲' },
  { code: 'PK', name: 'Panama', emoji: '🇵🇰' },
  { code: 'PW', name: 'Papua New Guinea', emoji: '🇵🇼' },
  { code: 'PS', name: 'Paraguay', emoji: '🇵🇸' },
  { code: 'PA', name: 'Peru', emoji: '🇵🇦' },
  { code: 'PG', name: 'Philippines', emoji: '🇵🇬' },
  { code: 'PY', name: 'Pitcairn', emoji: '🇵🇾' },
  { code: 'PE', name: 'Poland', emoji: '🇵🇪' },
  { code: 'PH', name: 'Portugal', emoji: '🇵🇭' },
  { code: 'PN', name: 'Puerto Rico', emoji: '🇵🇳' },
  { code: 'PL', name: 'Qatar', emoji: '🇵🇱' },
  { code: 'PT', name: 'R\u00e9union', emoji: '🇵🇹' },
  { code: 'PR', name: 'Romania', emoji: '🇵🇷' },
  { code: 'QA', name: 'Russian Federation', emoji: '🇶🇦' },
  { code: 'RE', name: 'Rwanda', emoji: '🇷🇪' },
  { code: 'RO', name: 'Saint Barth\u00e9lemy', emoji: '🇷🇴' },
  { code: 'RU', name: 'Saint Helena', emoji: '🇷🇺' },
  { code: 'RW', name: 'Saint Kitts and Nevis', emoji: '🇷🇼' },
  { code: 'BL', name: 'Saint Lucia', emoji: '🇧🇱' },
  { code: 'SH', name: 'Saint Martin (French part)', emoji: '🇸🇭' },
  { code: 'KN', name: 'Saint Pierre and Miquelon', emoji: '🇰🇳' },
  { code: 'LC', name: 'Saint Vincent and the Grenadines', emoji: '🇱🇨' },
  { code: 'MF', name: 'Samoa', emoji: '🇲🇫' },
  { code: 'PM', name: 'San Marino', emoji: '🇵🇲' },
  { code: 'VC', name: 'Sao Tome and Principe', emoji: '🇻🇨' },
  { code: 'WS', name: 'Saudi Arabia', emoji: '🇼🇸' },
  { code: 'SM', name: 'Senegal', emoji: '🇸🇲' },
  { code: 'ST', name: 'Serbia', emoji: '🇸🇹' },
  { code: 'SA', name: 'Seychelles', emoji: '🇸🇦' },
  { code: 'SN', name: 'Sierra Leone', emoji: '🇸🇳' },
  { code: 'RS', name: 'Singapore', emoji: '🇷🇸' },
  { code: 'SC', name: 'Sint Maarten (Dutch part)', emoji: '🇸🇨' },
  { code: 'SL', name: 'Slovakia', emoji: '🇸🇱' },
  { code: 'SG', name: 'Slovenia', emoji: '🇸🇬' },
  { code: 'SX', name: 'Solomon Islands', emoji: '🇸🇽' },
  { code: 'SK', name: 'Somalia', emoji: '🇸🇰' },
  { code: 'SI', name: 'South Africa', emoji: '🇸🇮' },
  { code: 'SB', name: 'South Georgia and the South Sandwich Islands', emoji: '🇸🇧' },
  { code: 'SO', name: 'South Sudan', emoji: '🇸🇴' },
  { code: 'ZA', name: 'Spain', emoji: '🇿🇦' },
  { code: 'GS', name: 'Sri Lanka', emoji: '🇬🇸' },
  { code: 'SS', name: 'Sudan', emoji: '🇸🇸' },
  { code: 'ES', name: 'Suriname', emoji: '🇪🇸' },
  { code: 'LK', name: 'Svalbard and Jan Mayen', emoji: '🇱🇰' },
  { code: 'SD', name: 'Swaziland', emoji: '🇸🇩' },
  { code: 'SR', name: 'Sweden', emoji: '🇸🇷' },
  { code: 'SJ', name: 'Switzerland', emoji: '🇸🇯' },
  { code: 'SZ', name: 'Syrian Arab Republic', emoji: '🇸🇿' },
  { code: 'SE', name: 'Taiwan', emoji: '🇸🇪' },
  { code: 'CH', name: 'Tajikistan', emoji: '🇨🇭' },
  { code: 'SY', name: 'Tanzania', emoji: '🇸🇾' },
  { code: 'TW', name: 'Thailand', emoji: '🇹🇼' },
  { code: 'TJ', name: 'Timor-Leste', emoji: '🇹🇯' },
  { code: 'TZ', name: 'Togo', emoji: '🇹🇿' },
  { code: 'TH', name: 'Tokelau', emoji: '🇹🇭' },
  { code: 'TL', name: 'Tonga', emoji: '🇹🇱' },
  { code: 'TG', name: 'Trinidad and Tobago', emoji: '🇹🇬' },
  { code: 'TK', name: 'Tunisia', emoji: '🇹🇰' },
  { code: 'TO', name: 'Turkey', emoji: '🇹🇴' },
  { code: 'TT', name: 'Turkmenistan', emoji: '🇹🇹' },
  { code: 'TN', name: 'Turks and Caicos Islands', emoji: '🇹🇳' },
  { code: 'TR', name: 'Tuvalu', emoji: '🇹🇷' },
  { code: 'TM', name: 'Uganda', emoji: '🇹🇲' },
  { code: 'TC', name: 'Ukraine', emoji: '🇹🇨' },
  { code: 'TV', name: 'United Arab Emirates', emoji: '🇹🇻' },
  { code: 'UG', name: 'United Kingdom', emoji: '🇺🇬' },
  { code: 'UA', name: 'United States', emoji: '🇺🇦' },
  { code: 'AE', name: 'United States Minor Outlying Islands', emoji: '🇦🇪' },
  { code: 'GB', name: 'Uruguay', emoji: '🇬🇧' },
  { code: 'US', name: 'Uzbekistan', emoji: '🇺🇸' },
  { code: 'UM', name: 'Vanuatu', emoji: '🇺🇲' },
  { code: 'UY', name: 'Venezuela', emoji: '🇺🇾' },
  { code: 'UZ', name: 'Viet Nam', emoji: '🇺🇿' },
  { code: 'VU', name: 'Virgin Islands, British', emoji: '🇻🇺' },
  { code: 'VE', name: 'Virgin Islands, U.S.', emoji: '🇻🇪' },
  { code: 'VN', name: 'Wallis and Futuna', emoji: '🇻🇳' },
  { code: 'VG', name: 'Western Sahara', emoji: '🇻🇬' },
  { code: 'VI', name: 'Yemen', emoji: '🇻🇮' },
  { code: 'WF', name: 'Zambia', emoji: '🇼🇫' },
  { code: 'EH', name: 'Zimbabwe', emoji: '🇪🇭' },
];

export const createCountries = async (prisma: PrismaClient) => {
  for (const country of countries) {
    await prisma.countryCodes.create({ data: { ...country } });
  }
};
