export * from './add-language.usecase';
export * from './create-university.usecase';
export * from './create-partner.usecase';
export * from './delete-language.usecase';
export * from './delete-partner.usecase';
export * from './get-languages.usecase';
export * from './get-universities.usecase';
export * from './get-university.usecase';
export * from './update-university-name.usecase';
