#
#   Copyright ou © ou Copr. Université de Lorraine, (2025)
#
#   Direction du Numérique de l'Université de Lorraine - SIED
#
#   Ce logiciel est un programme informatique servant à rendre accessible
#   sur mobile et sur internet l'application ULEP (University Language
#   Exchange Programme) aux étudiants et aux personnels des universités
#   parties prenantes.
#
#   Ce logiciel est régi par la licence CeCILL 2.1, soumise au droit français
#   et respectant les principes de diffusion des logiciels libres. Vous pouvez
#   utiliser, modifier et/ou redistribuer ce programme sous les conditions
#   de la licence CeCILL telle que diffusée par le CEA, le CNRS et INRIA
#   sur le site "http://cecill.info".
#
#   En contrepartie de l'accessibilité au code source et des droits de copie,
#   de modification et de redistribution accordés par cette licence, il n'est
#   offert aux utilisateurs qu'une garantie limitée. Pour les mêmes raisons,
#   seule une responsabilité restreinte pèse sur l'auteur du programme, le
#   titulaire des droits patrimoniaux et les concédants successifs.
#
#   À cet égard, l'attention de l'utilisateur est attirée sur les risques
#   associés au chargement, à l'utilisation, à la modification et/ou au
#   développement et à la reproduction du logiciel par l'utilisateur étant
#   donné sa spécificité de logiciel libre, qui peut le rendre complexe à
#   manipuler et qui le réserve donc à des développeurs et des professionnels
#   avertis possédant des connaissances informatiques approfondies. Les
#   utilisateurs sont donc invités à charger et à tester l'adéquation du
#   logiciel à leurs besoins dans des conditions permettant d'assurer la
#   sécurité de leurs systèmes et/ou de leurs données et, plus généralement,
#   à l'utiliser et à l'exploiter dans les mêmes conditions de sécurité.
#
#   Le fait que vous puissiez accéder à cet en-tête signifie que vous avez
#   pris connaissance de la licence CeCILL 2.1, et que vous en avez accepté les
#   termes.
#

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop" ||  $CI_COMMIT_BRANCH == "ci" # Supprimer ci

stages:
  - packages

# CI de package
.package ci:
  stage: packages
  trigger:
    include: .gitlab-ci/package-ci.yml
    strategy: depend

# CI de l'admin
🧩 admin:
  extends: .package ci
  variables:
    WORKING_DIR: admin
    IMAGE_NAME: ulep/admin
    DOCKERFILE_PATH: .gitlab-ci/Dockerfile.admin
    # DOCKER_TARGET: admin_prod # Génère une erreur : ERR_PNPM_BROKEN_LOCKFILE  The lockfile at "/srv/app/pnpm-lock.yaml" is broken: duplicated mapping key (1755:3)
    LINT: enabled
    # Optimisation mémoire suite aux limitations du pod infra
    GENERATE_SOURCEMAP: "false"
    DISABLE_ESLINT_PLUGIN: "true"
    NODE_OPTIONS: "--max-old-space-size=1536"
  rules:
    - changes:
        - admin/**/*

# CI de l'initialisation API
🧩 api init:
  extends: .package ci
  variables:
    WORKING_DIR: api
    IMAGE_NAME: ulep/api-init
    DOCKER_TARGET: api_init
  rules:
    - changes:
        - api/libs/common/src/database/**/*

# CI de l'API
🧩 api:
  extends: .package ci
  variables:
    WORKING_DIR: api
    IMAGE_NAME: ulep/api
    DOCKERFILE_PATH: .gitlab-ci/Dockerfile.api
    DOCKER_TARGET: api_ul
    # DOCKER_TARGET: api_prod
    LINT: enabled
    TEST: enabled
  rules:
    - changes:
        - api/**/*

# CI du thème UL Keycloak
🧩 auth ul theme:
  extends: .package ci
  variables:
    WORKING_DIR: docker/keycloak
    IMAGE_NAME: ulep/auth-ul-theme
    TAG: "1.7"
  rules:
    - changes:
        - docker/keycloak/**/*

# CI de la webapp
🧩 webapp:
  extends: .package ci
  variables:
    WORKING_DIR: app
    IMAGE_NAME: ulep/webapp
  rules:
    - changes:
        - app/**/*

# CI du chat
🧩 chat:
  extends: .package ci
  variables:
    WORKING_DIR: chat
    IMAGE_NAME: ulep/chat
  rules:
    - changes:
        - chat/**/*
