#
#   Copyright ou © ou Copr. Université de Lorraine, (2025)
#
#   Direction du Numérique de l'Université de Lorraine - SIED
#
#   Ce logiciel est un programme informatique servant à rendre accessible
#   sur mobile et sur internet l'application ULEP (University Language
#   Exchange Programme) aux étudiants et aux personnels des universités
#   parties prenantes.
#
#   Ce logiciel est régi par la licence CeCILL 2.1, soumise au droit français
#   et respectant les principes de diffusion des logiciels libres. Vous pouvez
#   utiliser, modifier et/ou redistribuer ce programme sous les conditions
#   de la licence CeCILL telle que diffusée par le CEA, le CNRS et INRIA
#   sur le site "http://cecill.info".
#
#   En contrepartie de l'accessibilité au code source et des droits de copie,
#   de modification et de redistribution accordés par cette licence, il n'est
#   offert aux utilisateurs qu'une garantie limitée. Pour les mêmes raisons,
#   seule une responsabilité restreinte pèse sur l'auteur du programme, le
#   titulaire des droits patrimoniaux et les concédants successifs.
#
#   À cet égard, l'attention de l'utilisateur est attirée sur les risques
#   associés au chargement, à l'utilisation, à la modification et/ou au
#   développement et à la reproduction du logiciel par l'utilisateur étant
#   donné sa spécificité de logiciel libre, qui peut le rendre complexe à
#   manipuler et qui le réserve donc à des développeurs et des professionnels
#   avertis possédant des connaissances informatiques approfondies. Les
#   utilisateurs sont donc invités à charger et à tester l'adéquation du
#   logiciel à leurs besoins dans des conditions permettant d'assurer la
#   sécurité de leurs systèmes et/ou de leurs données et, plus généralement,
#   à l'utiliser et à l'exploiter dans les mêmes conditions de sécurité.
#
#   Le fait que vous puissiez accéder à cet en-tête signifie que vous avez
#   pris connaissance de la licence CeCILL 2.1, et que vous en avez accepté les
#   termes.
#

scripts:
  - &install_pnpm
    name: Install pnpm
    script: |
        npm install -g pnpm
  - &install_pnpm_dependency
    name: Install pnpm dependencies for Ionic project
    script: |
        cd app && pnpm install --no-frozen-lockfile
  - &install_cocoapod
    name: Cocoapods installation
    script: |
        cd app/ios/App && pod install
  - &pnpm_build
    name: Build pnpm
    script: |
        cd app && pnpm build
  - &linter
    name: Linter
    script: |
        cd app && pnpm lint
  - &setup_preprod_google_services_android
    name: Add google-services.json in android
    script: |
        echo $GOOGLE_SERVICES_ANDROID_PREPROD | base64 --decode > $CM_BUILD_DIR/app/android/app/google-services.json
  - &setup_preprod_google_services_ios
    name: Add GoogleService-Info.plist in ios
    script: |
        echo $GOOGLE_SERVICES_IOS_PREPROD | base64 --decode > $CM_BUILD_DIR/app/ios/GoogleService-Info.plist
  - &test_e2e
    name: Test end to end
    script: |
        cd app
        pnpm preview --port 8101 &
        sleep 5
        pnpm test.e2e
  - &unit_test
    name: Unit Test
    script: |
        cd app && pnpm test.unit
  - &set_sdk_location
    name: Set Android SDK location
    script: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/app/android/local.properties"
  - &update_dependency_android
    name: Update dependencies and copy web assets to native project
    script: |
        cd app && npx cap sync android # <- update native dependencies and copy web assets to native project
  # - &setup_xcode
  #   name: Set up code signing settings on Xcode project
  #   script: |
  #       cd app && xcode-project use-profiles
  - &increment_build_number
    name: Increment build number
    script: |
        cd $CM_BUILD_DIR/app/ios/App
        agvtool new-version -all $BUILD_NUMBER
  - &add_staging_environment_file
    name: Add environment file
    script: |
        cat >> "app/.env" <<EOF
        VITE_UL_API_URL=$VITE_UL_API_URL
        VITE_SENTRY_DSN=$VITE_SENTRY_DSN
        VITE_JITSI_URL=$VITE_JITSI_URL
        VITE_UL_CHAT_URL=$VITE_UL_CHAT_URL
        VITE_UL_SOCKET_CHAT_URL=$VITE_UL_SOCKET_CHAT_URL
        ENV=staging
        EOF
  - &setup_keystore
    name: Setup keystore
    script: |
        cat >> "$CM_BUILD_DIR/app/android/key.properties" <<EOF
        storePassword=$CM_KEYSTORE_PASSWORD
        keyPassword=$CM_KEY_PASSWORD
        keyAlias=$CM_KEY_ALIAS
        storeFile=$CM_KEYSTORE_PATH
        EOF
  # - &build_ipa
  #   name: Build ipa for distribution
  #   script: |
  #       cd $CM_BUILD_DIR/app
  #       xcode-project build-ipa \
  #         --workspace "$XCODE_WORKSPACE" \
  #         --scheme "$XCODE_SCHEME"
  - &build_apk
    name: Build Android release
    script: |
        cd $CM_BUILD_DIR/app/android
        ./gradlew assembleStagingRelease \
          -PversionCode=$BUILD_NUMBER
workflows:
    # ionic-capacitor-ios-workflow:
    #     name: Build and Deploy IOS
    #     max_build_duration: 120
    #     instance_type: mac_mini_m1
    #     integrations:
    #         app_store_connect: theTribe
    #     environment:
    #         ios_signing:
    #             distribution_type: app_store
    #             bundle_identifier: fr.univlorraine.ulep
    #         vars:
    #             # Ionic Xcode worskspace and scheme
    #             XCODE_WORKSPACE: "ios/App/App.xcworkspace"
    #             XCODE_SCHEME: "staging"
    #             APP_STORE_APP_ID: $APP_STORE_APP_ID
    #         node: 16.14.0
    #         xcode: 15.0
    #         cocoapods: 1.11.2
    #     triggering:
    #         events:
    #             - push
    #         branch_patterns:
    #             - pattern: develop
    #               include: true
    #               source: true
    #     scripts:
    #         - *add_staging_environment_file
    #         - *setup_preprod_google_services_ios
    #         - *install_pnpm
    #         - *install_pnpm_dependency
    #         - *pnpm_build
    #         - *update_dependency
    #         - *install_cocoapod
    #         - *setup_xcode
    #         - *increment_build_number
    #         - *build_ipa
    #     artifacts:
    #         - $CM_BUILD_DIR/app/build/ios/ipa/*.ipa
    #         - /tmp/xcodebuild_logs/*.log
    #         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    #         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    #     publishing:
    #         app_store_connect:
    #             auth: integration

    #             # Configuration related to TestFlight (optional)
    #             # Note: This action is performed during post-processing.
    #             submit_to_testflight: true

    #             # Configuration related to App Store (optional)
    #             # Note: This action is performed during post-processing.
    #             submit_to_app_store: false

    ionic-capacitor-android-workflow:
        name: Build and Deploy Android
        max_build_duration: 120
        instance_type: linux_x2
        environment:
            android_signing:
              - theTribe
            groups:
              - firebase_credentials
              - staging
            vars:
                PACKAGE_NAME: "fr.univlorraine.ulep"
                # GOOGLE_PLAY_TRACK: alpha
            node: 20.18.0
            java: 21.0.1
        triggering:
            events:
              - push
            branch_patterns:
              - pattern: develop
                include: true
                source: true
        scripts:
          - *add_staging_environment_file
          - *setup_preprod_google_services_android
          - *setup_keystore
          - *install_pnpm
          - *install_pnpm_dependency
          - *pnpm_build
          - *set_sdk_location
          - *update_dependency_android
          - *build_apk
        artifacts:
          - $CM_BUILD_DIR/app/android/app/build/outputs/**/*.apk
        publishing:
            firebase:
                firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
                android:
                    app_id: 1:305758228479:android:b66dc123578d8fa17321ca
                    groups:
                      - android-testers

    analyse-and-test:
        name: Ionic analyse and test
        max_build_duration: 120
        instance_type: linux_x2
        cache:
            cache_paths:
              - $CM_BUILD_DIR/mobile/ios/Pods
              - $CM_BUILD_DIR/mobile/node_modules
        environment:
            node: 18.12.0
            xcode: 15.0
            cocoapods: 1.12.1
            groups:
              - staging
            android_signing:
              - theTribe
              # ios_signing:
              #   provisioning_profiles:
              #   - profile: ulep
              #     environment_variable: ~/Library/MobileDevice/Provisioning Profiles
              #   certificates:
              #     - certificate: theTribe
              #       environment_variable: ~/Library/MobileDevice/Certificates
            vars:
                BUNDLE_ID: "fr.univlorraine.ulep"
        triggering:
            events:
              - push
            branch_patterns:
              - pattern: "*"
                include: true
                source: true
              - pattern: "develop"
                include: false
                source: false
              - pattern: "main"
                include: false
                source: false
        when:
            changeset:
                includes:
                  - "app/"
        scripts:
          - *install_pnpm
          - *install_pnpm_dependency
          - *setup_preprod_google_services_android
          - *pnpm_build
          - *linter
          - *unit_test
