scripts:
  - &install_pnpm
    name: Install pnpm
    script: |
      npm install -g pnpm
  - &install_pnpm_dependency
    name: Install pnpm dependencies for Ionic project
    script: |
      cd app && pnpm install
  - &install_cocoapod
    name: Cocoapods installation
    script: |
      cd app/ios/App && pod install
  - &pnpm_build
    name: Build pnpm
    script: |
      cd app && pnpm build
  - &linter
    name: Linter
    script: |
      cd app && pnpm lint
  - &test_e2e
    name: Test end to end
    script: |
      cd app
      pnpm preview --port 8101 &
      sleep 5
      pnpm test.e2e
  - &unit_test
    name: Unit Test
    script: |
      cd app && pnpm test.unit
  - &set_sdk_location
    name: Set Android SDK location
    script: |
      echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/app/android/local.properties"
  - &update_dependency
    name: Update dependencies and copy web assets to native project
    script: |
      cd app && npx cap sync # <- update native dependencies and copy web assets to native project
  - &setup_xcode
    name: Set up code signing settings on Xcode project
    script: |
      cd app && xcode-project use-profiles
  - &increment_build_number
    name: Increment build number
    script: |
      cd $CM_BUILD_DIR/app/ios/App
      LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_ID")
      agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
  - &add_staging_environment_file
      name: Add environment file
      script: |
          cat >> "app/.env" <<EOF
          VITE_API_URL=$VITE_API_URL
          VITE_KEYCLOAK_URL=$VITE_KEYCLOAK_URL
          ENV=staging
          EOF
  - &setup_keystore
      name: Setup keystore
      script: |
          cat >> "$CM_BUILD_DIR/app/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF
  - &build_ipa
    name: Build ipa for distribution
    script: |
      cd $CM_BUILD_DIR/app
      xcode-project build-ipa \
        --workspace "$XCODE_WORKSPACE" \
        --scheme "$XCODE_SCHEME"
  - &build_apk
    name: Build Android release
    script: |
      cd $CM_BUILD_DIR/app/android
      ./gradlew assembleStagingRelease \
        -PversionCode=$BUILD_NUMBER 
workflows:
  ionic-capacitor-ios-workflow:
    name: Build and Deploy IOS
    max_build_duration: 120
    instance_type: mac_pro
    integrations:
      app_store_connect: theTribe
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.ionic.etandem.staging
      vars:
        # Ionic Xcode worskspace and scheme
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "staging"
        APP_STORE_APP_ID: $APP_STORE_APP_ID
      node: 16.14.0
      xcode: 14.2
      cocoapods: 1.11.2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    scripts:
      - *add_staging_environment_file
      - *install_pnpm
      - *install_pnpm_dependency
      - *pnpm_build
      - *update_dependency
      - *install_cocoapod
      - *setup_xcode
      - *increment_build_number
      - *build_ipa
    artifacts:
      - $CM_BUILD_DIR/app/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false


  ionic-capacitor-android-workflow:
    name: Build and Deploy Android
    max_build_duration: 120
    instance_type: mac_pro
    environment:
      android_signing:
        - theTribe
      groups:
        - firebase_credentials
        - staging
      vars:
        PACKAGE_NAME: "com.ionic.etandem.staging"
        # GOOGLE_PLAY_TRACK: alpha
      node: 16.14.0
      xcode: 14.2
      java: 19.0.1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    scripts:
      - *add_staging_environment_file
      - *setup_keystore
      - *install_pnpm
      - *install_pnpm_dependency
      - *pnpm_build
      - *set_sdk_location
      - *update_dependency
      - *build_apk
    artifacts:
      - $CM_BUILD_DIR/app/android/app/build/outputs/**/*.apk
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: 1:305758228479:android:6fc469b7f02de1cb7321ca
          groups: 
            - android-testers

  analyse-and-test:
    name: Ionic analyse and test
    max_build_duration: 120
    instance_type: mac_pro
    cache:
      cache_paths:
        - $CM_BUILD_DIR/mobile/ios/Pods
        - $CM_BUILD_DIR/mobile/node_modules
    environment:
      node: 16.14.0
      xcode: 14.2
      cocoapods: 1.11.2
      android_signing:
        - theTribe
      ios_signing:
        provisioning_profiles:
          - profile: ulep
            environment_variable: ~/Library/MobileDevice/Provisioning Profiles
        certificates:
          - certificate: theTribe
            environment_variable: ~/Library/MobileDevice/Certificates
      vars:
        BUNDLE_ID: 'com.ionic.etandem.staging'
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
        - pattern: 'develop'
          include: false
          source: false
        - pattern: 'main'
          include: false
          source: false
    when:
      changeset:
        includes:
          - 'app/'
    scripts:
      - *install_pnpm
      - *install_pnpm_dependency
      - *pnpm_build
      - *linter
      - *test_e2e
      - *unit_test