import { Module, Provider } from '@nestjs/common';
import { CronService } from 'src/core/services/CronService';
import {
  CreateCampusUsecase,
  DeleteCampusUsecase,
  GetCampusByIdUsecase,
  GetCampusUsecase,
  UpdateCampusUsecase,
} from 'src/core/usecases/campus';
import { FindAllSuggestedLanguageUsecase } from 'src/core/usecases/language/find-all-suggested-language.usecase';
import { DeleteObjectiveImageUsecase } from 'src/core/usecases/media/delete-objective-image.usecase';
import { UploadObjectiveImageUsecase } from 'src/core/usecases/media/upload-objective-image.usecase';
import { SendMessageNotificationUsecase } from 'src/core/usecases/notifications';
import { UpdateObjectiveUsecase } from 'src/core/usecases/objective/update-objective.usecase';
import { GetVocabularyListPdfUsecase } from 'src/core/usecases/vocabulary/get-vocabulary-list-pdf.usecase';
import { ProvidersModule } from 'src/providers/providers.module';
import { MatchScorer } from './services/MatchScorer';
import {
  AddDeviceUsecase,
  AddLanguageRequestUsecase,
  CountAllSuggestedLanguageUsecase,
  CreateActivityThemeCategoryUsecase,
  CreateActivityThemeUsecase,
  CreateActivityUsecase,
  CreateAdministratorUsecase,
  CreateInterestCategoryUsecase,
  CreateInterestUsecase,
  CreateLearningLanguageUseCase,
  CreateNewsUsecase,
  CreateObjectiveUsecase,
  CreateOrUpdateTestedLanguageUsecase,
  CreatePartnerUniversityUsecase,
  CreateProfileUsecase,
  CreateQuestionUsecase,
  CreateReportCategoryUsecase,
  CreateReportMessageUsecase,
  CreateReportUsecase,
  CreateTandemUsecase,
  CreateTestUsecase,
  CreateUniversityUsecase,
  CreateUnsubscribeReportUsecase,
  CreateUserUsecase,
  CreateVocabularyListUsecase,
  CreateVocabularyUsecase,
  DeleteActivityThemeCategoryUsecase,
  DeleteActivityThemeUsecase,
  DeleteActivityUsecase,
  DeleteAdministratorUsecase,
  DeleteAudioVocabularyActivityUsecase,
  DeleteAudioVocabularyUsecase,
  DeleteAvatarUsecase,
  DeleteImageActivityUsecase,
  DeleteInterestCategoryUsecase,
  DeleteInterestUsecase,
  DeleteMediaActivityUsecase,
  DeleteNewsImageUsecase,
  DeleteNewsUsecase,
  DeleteObjectiveUsecase,
  DeleteProfileUsecase,
  DeleteQuestionUsecase,
  DeleteReportCategoryUsecase,
  DeleteReportUsecase,
  DeleteTestUsecase,
  DeleteUniversityUsecase,
  DeleteUserUsecase,
  DeleteVocabularyListUsecase,
  DeleteVocabularyUsecase,
  FindAllLanguageCodeUsecase,
  FindAllObjectiveUsecase,
  FindAllVocabularyFromListIdUsecase,
  FindAllVocabularyListUsecase,
  FindOneObjectiveUsecase,
  GenerateConversationsUsecase,
  GenerateTandemsUsecase,
  GetActivitiesUsecase,
  GetActivityThemeCategoryUsecase,
  GetActivityThemeUsecase,
  GetActivityUsecase,
  GetAdministratorsUsecase,
  GetAdministratorUsecase,
  GetAllActivityThemesUsecase,
  GetAllConversationsFromUserIdUsecase,
  GetCategoriesUsecase,
  GetCountriesUniversitiesUsecase,
  GetCountriesUsecase,
  GetInstanceUsecase,
  GetInterestCategoryUsecase,
  GetInterestsByCategoriesUsecase,
  GetInterestUsecase,
  GetLearningLanguageMatchesUsecase,
  GetLearningLanguageOfIdUsecase,
  GetLearningLanguageOfProfileUsecase,
  GetLearningLanguagesUsecase,
  GetLevelsUsecase,
  GetMediaObjectUsecase,
  GetMessagesFromConversationUsecase,
  GetNewsUsecase,
  GetOneNewsUsecase,
  GetOtherUserEmailInTandemUsecase,
  GetPartnersToUniversityUsecase,
  GetProfileByUserIdUsecase,
  GetProfilesUsecase,
  GetProfilesWithTandemsProfilesUsecase,
  GetProfileUsecase,
  GetProfileWithTandemsProfilesUsecase,
  GetQuestionsByLevelUsecase,
  GetQuestionsUsecase,
  GetQuestionUsecase,
  GetReportCategoryByIdUsecase,
  GetReportsByStatusUsecase,
  GetReportUsecase,
  GetTandemsByIdsUsecase,
  GetTandemsForProfileUsecase,
  GetTandemsUsecase,
  GetTestsUsecase,
  GetTestUsecase,
  GetUniversitiesUsecase,
  GetUniversityDivisionsUsecase,
  GetUniversityUsecase,
  GetUserPersonalData,
  GetUsersUsecase,
  GetUserUsecase,
  RefuseTandemUsecase,
  UpdateActivityThemeCategoryUsecase,
  UpdateActivityThemeUsecase,
  UpdateActivityUsecase,
  UpdateAdministratorUsecase,
  UpdateCountryStatusUsecase,
  UpdateInstanceUsecase,
  UpdateInterestCategoryUsecase,
  UpdateInterestUsecase,
  UpdateLanguageCodeUsecase,
  UpdateNewsUsecase,
  UpdateProfileUsecase,
  UpdateQuestionUsecase,
  UpdateReportCategoryUsecase,
  UpdateReportStatusUsecase,
  UpdateTandemUsecase,
  UpdateUniversityUsecase,
  UpdateUserUsecase,
  UpdateVocabularyListUsecase,
  UpdateVocabularyUsecase,
  UploadAdminAvatarUsecase,
  UploadAudioVocabularyActivityUsecase,
  UploadAudioVocabularyUsecase,
  UploadAvatarUsecase,
  UploadImageActivityUsecase,
  UploadMediaActivityUsecase,
  UploadNewsImageUsecase,
  UploadUniversityImageUsecase,
} from './usecases';
import { GetJitsiTokenUsecase } from './usecases/jitsi/get-jitsi-token.usecase';
import { DeleteLearningLanguageUsecase } from './usecases/learningLanguage/delete-learning-langugage.usecase';
import { GetLearningLanguageTandemUsecase } from './usecases/learningLanguage/getLearningLanguageTandem.usecase';
import { UploadInstanceDefaultCertificateUsecase } from './usecases/media/upload-instance-default-certificate.usecase';
import { UploadUniversityDefaultCertificateUsecase } from './usecases/media/upload-university-default-certificate.usecase';
import { ArchiveTandemsAndDeleteUsersUsecase } from './usecases/purges/archive-tandems.usecase';
import { LogoutAllSessionsUsecase } from './usecases/security/logout-all-sessions.usecase';
import { ResetPasswordUsecase } from './usecases/security/reset-password.usecase';
import { CancelSessionUsecase } from './usecases/session/cancel-session.usecase';
import { CreateSessionUsecase } from './usecases/session/create-session.usecase';
import { GetSessionsForProfileUsecase } from './usecases/session/get-sessions-for-profile.usecase';
import { UpdateSessionUsecase } from './usecases/session/update-session.usecase';
import { ValidateTandemUsecase } from './usecases/tandem/validate-tandem.usecase';
import { GetKeycloakAdminGroupsUsecase } from './usecases/user/get-keycloak-admin-groups.usecase';
import { RevokeSessionsUsecase } from './usecases/user/revoke-sessions.usecase';

const usecases: Provider[] = [
  // Activity
  CreateActivityUsecase,
  GetAllActivityThemesUsecase,
  GetActivityUsecase,
  GetActivitiesUsecase,
  GetActivityThemeCategoryUsecase,
  CreateActivityThemeCategoryUsecase,
  CreateActivityThemeUsecase,
  GetActivityThemeUsecase,
  DeleteActivityUsecase,
  DeleteActivityThemeCategoryUsecase,
  DeleteActivityThemeUsecase,
  UpdateActivityThemeCategoryUsecase,
  UpdateActivityThemeUsecase,
  UpdateActivityUsecase,
  UpdateActivityStatusUsecase,
  GetAllActivitiesByAdminUsecase,
  //Campus
  CreateCampusUsecase,
  DeleteCampusUsecase,
  GetCampusUsecase,
  GetCampusByIdUsecase,
  UpdateCampusUsecase,
  // Countries
  GetCountriesUsecase,
  GetCountriesUniversitiesUsecase,
  UpdateCountryStatusUsecase,
  // Interest
  CreateInterestCategoryUsecase,
  CreateInterestUsecase,
  DeleteInterestCategoryUsecase,
  DeleteInterestUsecase,
  GetInterestsByCategoriesUsecase,
  GetInterestUsecase,
  GetInterestCategoryUsecase,
  UpdateInterestCategoryUsecase,
  UpdateInterestUsecase,
  // Languages
  AddLanguageRequestUsecase,
  CountAllSuggestedLanguageUsecase,
  FindAllLanguageCodeUsecase,
  FindAllSuggestedLanguageUsecase,
  UpdateLanguageCodeUsecase,
  // Media
  GetMediaObjectUsecase,
  DeleteAudioVocabularyUsecase,
  DeleteObjectiveImageUsecase,
  DeleteMediaActivityUsecase,
  DeleteImageActivityUsecase,
  DeleteAudioVocabularyActivityUsecase,
  UploadAvatarUsecase,
  UploadAdminAvatarUsecase,
  UploadObjectiveImageUsecase,
  UploadUniversityImageUsecase,
  UploadAudioVocabularyUsecase,
  UploadImageActivityUsecase,
  UploadAudioVocabularyActivityUsecase,
  UploadMediaActivityUsecase,
  UploadInstanceDefaultCertificateUsecase,
  UploadUniversityDefaultCertificateUsecase,
  // News
  GetNewsUsecase,
  GetOneNewsUsecase,
  CreateNewsUsecase,
  UpdateNewsUsecase,
  DeleteNewsUsecase,
  UploadNewsImageUsecase,
  DeleteNewsImageUsecase,
  // Objectives
  CreateObjectiveUsecase,
  DeleteObjectiveUsecase,
  FindAllObjectiveUsecase,
  FindOneObjectiveUsecase,
  UpdateObjectiveUsecase,
  // Proficiency
  CreateQuestionUsecase,
  CreateTestUsecase,
  DeleteQuestionUsecase,
  DeleteTestUsecase,
  GetQuestionUsecase,
  GetQuestionsUsecase,
  GetQuestionsByLevelUsecase,
  GetLevelsUsecase,
  GetTestUsecase,
  GetTestsUsecase,
  UpdateQuestionUsecase,
  // Reports
  CreateUnsubscribeReportUsecase,
  CreateReportCategoryUsecase,
  CreateReportUsecase,
  CreateReportMessageUsecase,
  DeleteReportCategoryUsecase,
  DeleteReportUsecase,
  GetCategoriesUsecase,
  GetReportCategoryByIdUsecase,
  GetReportUsecase,
  GetReportsByStatusUsecase,
  UpdateReportStatusUsecase,
  UpdateReportCategoryUsecase,
  // Profiles
  CreateOrUpdateTestedLanguageUsecase,
  CreateProfileUsecase,
  GetTandemsForProfileUsecase,
  GetProfileByUserIdUsecase,
  GetProfilesUsecase,
  GetProfilesWithTandemsProfilesUsecase,
  GetProfileWithTandemsProfilesUsecase,
  GetProfileUsecase,
  DeleteAvatarUsecase,
  DeleteProfileUsecase,
  CreateLearningLanguageUseCase,
  UpdateProfileUsecase,
  // LearningLanguages
  GetLearningLanguagesUsecase,
  GetLearningLanguageOfIdUsecase,
  GetLearningLanguageOfProfileUsecase,
  GetLearningLanguageTandemUsecase,
  DeleteLearningLanguageUsecase,
  // History Tandem
  GetOtherUserEmailInTandemUsecase,
  // Tandems
  CreateTandemUsecase,
  GenerateTandemsUsecase,
  GetTandemsUsecase,
  GetTandemsByIdsUsecase,
  GetLearningLanguageMatchesUsecase,
  ValidateTandemUsecase,
  RefuseTandemUsecase,
  UpdateTandemUsecase,
  // Universities
  CreatePartnerUniversityUsecase,
  CreateUniversityUsecase,
  DeleteUniversityUsecase,
  GetPartnersToUniversityUsecase,
  GetUniversitiesUsecase,
  GetUniversityUsecase,
  UpdateUniversityUsecase,
  GetUniversityDivisionsUsecase,
  // Users
  AddDeviceUsecase,
  CreateAdministratorUsecase,
  CreateUserUsecase,
  DeleteAdministratorUsecase,
  DeleteUserUsecase,
  GetAdministratorUsecase,
  GetAdministratorsUsecase,
  GetUsersUsecase,
  GetUserUsecase,
  UpdateUserUsecase,
  UpdateAdministratorUsecase,
  ArchiveTandemsAndDeleteUsersUsecase,
  RevokeSessionsUsecase,
  GetUserPersonalData,
  GetKeycloakAdminGroupsUsecase,
  // Instance
  GetInstanceUsecase,
  UpdateInstanceUsecase,
  // Security
  ResetPasswordUsecase,
  GetJitsiTokenUsecase,
  LogoutAllSessionsUsecase,
  // Notifications
  SendMessageNotificationUsecase,
  // Chat
  GenerateConversationsUsecase,
  GetAllConversationsFromUserIdUsecase,
  GetMessagesFromConversationUsecase,
  // Vocabulary
  CreateVocabularyUsecase,
  CreateVocabularyListUsecase,
  DeleteVocabularyUsecase,
  DeleteVocabularyListUsecase,
  FindAllVocabularyFromListIdUsecase,
  FindAllVocabularyListUsecase,
  UpdateVocabularyUsecase,
  UpdateVocabularyListUsecase,
  GetVocabularyListPdfUsecase,
  // Session
  CancelSessionUsecase,
  CreateSessionUsecase,
  GetSessionsForProfileUsecase,
  UpdateSessionUsecase,
];

const services: Provider[] = [MatchScorer, CronService];

@Module({
  imports: [ProvidersModule],
  providers: [...usecases, ...services],
  exports: [...usecases, ...services],
})
export class CoreModule {}
