import { Module, Provider } from '@nestjs/common';
import { ProvidersModule } from 'src/providers/providers.module';
import { MatchScorer } from './services/MatchScorer';
import {
  AddLanguageRequestUsecase,
  AddLanguageUsecase,
  AskForAccountDeletionUsecase,
  CreateInterestCategoryUsecase,
  CreateInterestUsecase,
  CreateObjectiveUsecase,
  CreatePartnerUniversityUsecase,
  CreateProfileUsecase,
  CreateQuestionUsecase,
  CreateReportCategoryUsecase,
  CreateReportUsecase,
  CreateTandemUsecase,
  CreateTestUsecase,
  CreateUniversityUsecase,
  CreateUserUsecase,
  DeleteInterestCategoryUsecase,
  DeleteInterestUsecase,
  DeleteLanguageUsecase,
  DeleteObjectiveUsecase,
  DeleteQuestionUsecase,
  DeleteReportCategoryUsecase,
  DeleteReportUsecase,
  DeleteTestUsecase,
  DeleteUniversityUsecase,
  DeleteUserUsecase,
  FindAllLanguageCodeUsecase,
  FindAllObjectiveUsecase,
  FindOneObjectiveUsecase,
  GenerateTandemsUsecase,
  GetCategoriesUsecase,
  GetCountriesUsecase,
  GetInterestsByCategoriesUsecase,
  GetLanguagesUsecase,
  GetLevelsUsecase,
  GetProfileByUserIdUsecase,
  GetProfileUsecase,
  GetProfilesUsecase,
  GetQuestionsByLevelUsecase,
  GetReportUsecase,
  GetReportsByStatusUsecase,
  GetTandemsForProfileUsecase,
  GetTandemsUsecase,
  GetTestUsecase,
  GetTestsUsecase,
  GetUniversitiesUsecase,
  GetUniversityUsecase,
  GetUserMatchUsecase,
  GetUserUsecase,
  GetUsersUsecase,
  UpdateCountryStatusUsecase,
  UpdateReportStatusUsecase,
  UpdateUniversityNameUsecase,
  UpdateUserUsecase,
  UploadAvatarUsecase,
} from './usecases';
import { UploadObjectiveImageUsecase } from 'src/core/usecases/media/upload-objective-image.usecase';
import { UpdateObjectiveUsecase } from 'src/core/usecases/objective/update-objective.usecase';
import { DeleteObjectiveImageUsecase } from 'src/core/usecases/media/delete-objective-image.usecase';

const usecases: Provider[] = [
  // Countries
  GetCountriesUsecase,
  UpdateCountryStatusUsecase,
  // Interest
  CreateInterestCategoryUsecase,
  CreateInterestUsecase,
  DeleteInterestCategoryUsecase,
  DeleteInterestUsecase,
  GetInterestsByCategoriesUsecase,
  // Languages
  AddLanguageRequestUsecase,
  FindAllLanguageCodeUsecase,
  // Media
  DeleteObjectiveImageUsecase,
  UploadAvatarUsecase,
  UploadObjectiveImageUsecase,
  // Objectives
  CreateObjectiveUsecase,
  DeleteObjectiveUsecase,
  FindAllObjectiveUsecase,
  FindOneObjectiveUsecase,
  UpdateObjectiveUsecase,
  // Proficiency
  CreateQuestionUsecase,
  CreateTestUsecase,
  DeleteQuestionUsecase,
  DeleteTestUsecase,
  GetQuestionsByLevelUsecase,
  GetLevelsUsecase,
  GetTestUsecase,
  GetTestsUsecase,
  // Reports
  CreateReportCategoryUsecase,
  CreateReportUsecase,
  DeleteReportCategoryUsecase,
  DeleteReportUsecase,
  GetCategoriesUsecase,
  GetReportUsecase,
  GetReportsByStatusUsecase,
  UpdateReportStatusUsecase,
  // Tandems
  CreateProfileUsecase,
  CreateTandemUsecase,
  GenerateTandemsUsecase,
  GetTandemsForProfileUsecase,
  GetProfileByUserIdUsecase,
  GetProfilesUsecase,
  GetProfileUsecase,
  GetTandemsUsecase,
  GetUserMatchUsecase,
  // Universities
  AddLanguageUsecase,
  CreatePartnerUniversityUsecase,
  CreateUniversityUsecase,
  DeleteLanguageUsecase,
  DeleteUniversityUsecase,
  GetLanguagesUsecase,
  GetUniversitiesUsecase,
  GetUniversityUsecase,
  UpdateUniversityNameUsecase,
  // Users
  AskForAccountDeletionUsecase,
  CreateUserUsecase,
  DeleteUserUsecase,
  GetUsersUsecase,
  GetUserUsecase,
  UpdateUserUsecase,
];

const services: Provider[] = [MatchScorer];

@Module({
  imports: [ProvidersModule],
  providers: [...usecases, ...services],
  exports: [...usecases, ...services],
})
export class CoreModule {}
