import CameraAdapterInterface from '../adapter/interfaces/CameraAdapter.interface';
import Configuration from '../domain/entities/Confirguration';
import AskForAccountDeletionUsecaseInterface from '../domain/interfaces/AskForAccountDeletionUsecase.interface';
import AskForLanguageUsecaseInterface from '../domain/interfaces/AskForLanguageUsecase.interface';
import AskForLearningLanguageUsecaseInterface from '../domain/interfaces/AskForLearningLanguageUsecase.interface';
import CreateOrUpdateTestedLanguageUsecaseInterface from '../domain/interfaces/CreateOrUpdateTestedLanguageUsecase.interface';
import CreateProfileUsecaseInterface from '../domain/interfaces/CreateProfileUsecase.interface';
import CreateReportUsecaseInterface from '../domain/interfaces/CreateReportUsecase.interface';
import CreateUserUsecaseInterface from '../domain/interfaces/CreateUserUsecase.interface';
import GetAllCountriesUsecaseInterface from '../domain/interfaces/GetAllCountriesUsecase.interface';
import GetAllGoalsUsecaseInterface from '../domain/interfaces/GetAllGoalsUsecase.interface';
import GetAllInterestCategoriessUsecase from '../domain/interfaces/GetAllInterestCategoriesUsecase.interface';
import GetAllLanguagesUsecaseInterface from '../domain/interfaces/GetAllLanguagesUsecase.interface';
import GetAllTandemsUsecaseInterface from '../domain/interfaces/GetAllTandemsUsecase.interface';
import GetAllUniversitiesUsecaseInterface from '../domain/interfaces/GetAllUniversitiesUsecase.interface';
import GetAllReportCategoriesUsecaseInterface from '../domain/interfaces/GetAlllReportCategoriesUsecase.interface';
import GetProfileUsecaseInterface from '../domain/interfaces/GetProfileUsecase.interface';
import GetQuizzByLevelUsecaseInterface from '../domain/interfaces/GetQuizzByLevelUsecase.interface';
import GetTokenFromCodeUsecaseInterface from '../domain/interfaces/AuthStandardFlow/GetTokenFromCodeUsecase.interface';
import GetUserUsecaseInterface from '../domain/interfaces/GetUserUsecase.interface';
import LoginUsecaseInterface from '../domain/interfaces/LoginUsecase.interface';
import ResetPasswordUsecaseInterface from '../domain/interfaces/ResetPasswordUsecase.interface';
import RetrievePersonInfoUsecaseInterface from '../domain/interfaces/RetrievePersonInfoUsecase.interface';
import UpdateAvatarUsecaseInterface from '../domain/interfaces/UpdateAvatarUsecase.interface';
import UpdateNotificationPermissionUsecaseInterface from '../domain/interfaces/UpdateNotificationPermissionUsecase.interface';
import GetUniversityInterface from '../domain/interfaces/GetUniversity.interface';
import GetMediaObjectUsecaseInterface from '../domain/interfaces/GetMediaObjectUsecase.interface';
import RevokeSessionsUsecaseInterface from '../domain/interfaces/RevokeSessionsUsecase.interface';
import GetInitialUrlUsecaseInterface from '../domain/interfaces/AuthStandardFlow/GetInitialUrlUsecase.interface';
import GetHistoricEmailPartnerUsecaseInterface from '../domain/interfaces/GetHistoricEmailPartnerUsecase.interface';
import BrowserAdapterInterface from '../adapter/interfaces/BrowserAdapter.interface';
import DeviceAdapterInterface from '../adapter/interfaces/DeviceAdapter.interface';
import GetUniversityLanguagesUsecaseInterface from '../domain/interfaces/GetUniversityLanguagesUsecase.interface';
import GetPartnersToUniversityUsecaseInterface from '../domain/interfaces/GetPartnersToUniversityUsecase.interface';
import EditProfileUsecaseInterface from '../domain/interfaces/EditProfileUsecase.interface';
import EditUserUsecaseInterface from '../domain/interfaces/EditUserUsecase.interface';
import NotificationAdapterInterface from '../adapter/interfaces/NotificationAdapter.interface';

export interface ConfigContextValueType {
    accessToken: string;
    askForAccountDeletion: AskForAccountDeletionUsecaseInterface;
    askForLanguage: AskForLanguageUsecaseInterface;
    askForLearningLanguage: AskForLearningLanguageUsecaseInterface;
    browserAdapter: BrowserAdapterInterface;
    cameraAdapter: CameraAdapterInterface;
    deviceAdapter: DeviceAdapterInterface;
    configuration: Configuration;
    createProfile: CreateProfileUsecaseInterface;
    createReport: CreateReportUsecaseInterface;
    createOrUpdateTestedLanguage: CreateOrUpdateTestedLanguageUsecaseInterface;
    createUser: CreateUserUsecaseInterface;
    editProfile: EditProfileUsecaseInterface;
    editUser: EditUserUsecaseInterface;
    getAllCountries: GetAllCountriesUsecaseInterface;
    getAllGoals: GetAllGoalsUsecaseInterface;
    getAllInterestCategories: GetAllInterestCategoriessUsecase;
    getAllLanguages: GetAllLanguagesUsecaseInterface;
    getAllReportCategories: GetAllReportCategoriesUsecaseInterface;
    getAllTandems: GetAllTandemsUsecaseInterface;
    getAllUniversities: GetAllUniversitiesUsecaseInterface;
    getHistoricEmailPartner: GetHistoricEmailPartnerUsecaseInterface;
    getMediaObject: GetMediaObjectUsecaseInterface;
    getPartnersToUniversity: GetPartnersToUniversityUsecaseInterface;
    getProfile: GetProfileUsecaseInterface;
    getQuizzByLevel: GetQuizzByLevelUsecaseInterface;
    getUser: GetUserUsecaseInterface;
    getUniversity: GetUniversityInterface;
    getUniversityLanguages: GetUniversityLanguagesUsecaseInterface;
    login: LoginUsecaseInterface;
    notificationAdapter: NotificationAdapterInterface;
    resetPassword: ResetPasswordUsecaseInterface;
    updateAvatar: UpdateAvatarUsecaseInterface;
    updateNotificationPermission: UpdateNotificationPermissionUsecaseInterface;
    retrievePerson: RetrievePersonInfoUsecaseInterface;
    getTokenFromCodeUsecase: GetTokenFromCodeUsecaseInterface;
    getInitialUrlUsecase: GetInitialUrlUsecaseInterface;
    revokeSessionsUsecase: RevokeSessionsUsecaseInterface;
}
